export let good_reviews = [
  " I bought this phone in Aug It is still perfect",
  " The phone is very good, I am satisfied with it",
  " Camera quality is great",
  " its camera is getting better day by day",
  " Excellent phone in low price",
  " Bettery is good It lasts long time",
  " Very fast charging phone, I loved it",
  " I have been using this phone for 1 year, still so smooth and nice",
  " It is still great, perfect and amazing battery life",
  " Overall it's beautiful",
  " Great gaming phone",
  " The Phone is very good and fast, I am ok with it",
  " In this price screen, battery and power is good",
  " All is well but photo quality is very bad",
  " Front camera is best that I have seen in recent times",
  " This is very nice phone in reasonable price",
  " The divice has excellent battery life and impressive design",
  " It is looking for the simplest Xiaomi phone",
  " I like the phone Cheep, with good performance, great camera and stylish design",
  " Very nice product and low costs",
  " It has good quality for a reasonable price",
  " I used different barnds of phone, but Samsung is best brand",
  " The keyboard performance is very good , compared its price",
  " The wireless keyboard works great and was easy to set up and start using",
  " The keyboard that I have been using has worked very well",
  " it's very comfortable to use",
  " RGB light looks so cool",
  " This mouse is comfortable to use",
  " Ihave been using it for 6 months, I suggest you to buy this keyboard",
  " Best mouse ever",
  " The mouse scrolling button works so smoothly",
  " Bettery quality is very good",
  " This keyboard is so good, it's waterproof which is a good thing for me",
  " The keyboard and mouse is beautiful",
  " The keys feel great to use,I'm enjoying to use it",
  " The mouse is so cute it changes colors every few seconds",
  " It's very attractive if you like the stainless steel look",
  " The mouse has a very nice feel",
  " The computer is amazing, one of the best laptop I have used",
  " Great computer, HP is well known for wonderful product",
  " I am 5th year of owning my 450, never had an issue with it",
  " I have been using HP laptop computers for over 20 years and love this barnd",
  " I am using external monitor with this laptop and it is a fantastic combination",
  " HP has a good battery life I have never had a problem with it",
  " The quality of their products are outstanding The equipment is normally an excellent price to purchase",
  " This is the best keyboard I have ever use Very smooth for typing, perfect size, and quick response",
  " Dell makes good quality laptop It's amazing, I loved it",
  " My dell laptop is still in good condition",
  "I have bought so many different brands of laptops over the years and Dell is clearly the best brand",
  " The pricing of a lot of the items are really well in Dell",
];

export let bad_reviews = [
  "Night mode does not work in front Camera",
  " WhatsApp video call quality is not so good",
  " I have this phone and I don't like it",
  " Camera quality is very bad, compared its camera pixels",
  " This phone has no face lock",
  " Procesor is very slow",
  " Worst procesor",
  " Processor is as slow as a week in the jail",
  " I bought this a month ago, it has hanging issue and  processor is very slow",
  " Heavy weight, I'm not satisfied of this shit",
  " Face and finger sensor is very bad",
  " Camera quality is so poor",
  " Doesn't support fast charging",
  " It became slow after using a couple months",
  " Screen is still really bright at lowest brightness setting",
  " Display got yellow after using few months",
  " The selfie camera is not good, what you get for 3mp camera",
  " it's not perfect for plying game",
  " It has heating issue",
  " Worst phone ever it has worst camera",
  " This one doesn't have a clear selfie, irritating, I hate this phone",
  " The keyboard price is very high, compared its performance",
  " The combo itself is nice looking, but it's cheaply made and you can feel it",
  " it's not comfortable to use",
  " RGB light does not work properly",
  " This mouse is not comfortable to use",
  " I suggest you not to buy this keyboard",
  " Worst mouse ever",
  " Its getting hot when using more than one hour",
  " The mouse scrolling button broke within the first week of buying it",
  " Sometime RGB doesn't light up",
  " This laptop has heating problem after using more than 2- hours",
  " Bettery quality is very bad",
  " I am using Asus laptop for  year, it has many issues",
  " I suggest you not to buy this Asus laptop",
  " I can't use external monitor in this laptop",
  " I had faced many problem with it",
  " This divice has Wi-Fi issues, it gets disconnected on its own which is highly irritating,  when other divice is still connencted",
  " It's one of the worst laptop from my side, I don't like the display and sounds quality",
  " This is very wrost mouse I have ever used",
  " with dell I am havibg the worst experience from one month and still struggling",
  " Never buy Dell if you want servic They are terrible",
  " Worst experience in my lif Bad product, worst costumer service",
  " Dell used to be a great bran Sadly the brand has no longer the quality",
  " Dell Technologies do not support their products very well",
  " I bought an Asus monitor, It's a wrost monitor",
  " Asus laptop sound is not working good, volume is not high",
  " A brand new laptop came with issues and it was not able to boot up, so it,s a wrost brand",
  " Acer is joke brand, I don't recommend Acer brand",
  " Never buy an Acer laptop, my device stopped working after 7 months",
];
