name: Build and Deploy
on:
  push:
    branches:
      - storybook-upgrade
jobs:
  deploy:
    name: Setup build and deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Run Build script
      uses: actions/setup-node@v1
      with:
        node-version: '18.18.0'
    - run: npm ci
    - run: npx lerna bootstrap --hoist --no-ci
    - run: npm run build:dist

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.6.2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build/v3
        CLEAN: true
        TARGET_FOLDER: docs
