on: ['deployment', 'repository_dispatch']
jobs:
  deploy:
    name: Setuo build and deploy
    runs-on: ubuntu-latest
    steps:
    - name: Public IP
      id: ip
      uses: haythem/public-ip@v1
      
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DOCTL_KEY }}
        
    - name: whitelist ip
      run: doctl compute firewall add-rules d82b3d3e-ded9-4dec-9e26-2769742ddb3e --inbound-rules protocol:tcp,ports:22,address:${{ steps.ip.outputs.ipv4 }}
    
